### ISSUE TITLE
asyncio.Taskgroup task cancellation policy can stall the server while crawling

### ISSUE THREAD

**Issue by antsinar** [antsinar/CrawlerAPI#1]
Stalling occured when the thread worker raised a ValueError: "." does not appear to be an IPv4 or IPv6 address.
Exceptions coming from the taskgroup inside crawler's build_graph function must be addressed.
Deside if its worth looking into trio as an alternative for handling async tasks.
[From python's documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.TaskGroup)
> The first time any of the tasks belonging to the group fails with an exception other than [asyncio.CancelledError](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError), the remaining tasks in the group are cancelled. No further tasks can then be added to the group. At this point, if the body of the async with statement is still active (i.e., [__aexit__()](https://docs.python.org/3/reference/datamodel.html#object.__aexit__) hasn’t been called yet), the task directly containing the async with statement is also cancelled. The resulting [asyncio.CancelledError](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError) will interrupt an await, but it will not bubble out of the containing async with statement.

**Comment by antsinar** [comment]
Example exception after 1.5 hours of crawling a single website:  
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4' coro=<TaskQueue.process_queue() done, defined at C:\<path>\crawler_api\src\processor.py:26> exception=ExceptionGroup('unhandled errors in a TaskGroup', [ValueError("'.' does not appear to be an IPv4 or IPv6 address")])>
  + Exception Group Traceback (most recent call last):
  |   File "C:\<path>\crawler_api\src\processor.py", line 39, in process_queue
  |     res = await loop.run_in_executor(self.pool, process_fn)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\<path>\Python313\Lib\concurrent\futures\thread.py", line 58, in run
  |     result = self.fn(*self.args, **self.kwargs)
  |   File "C:\<path>\crawler_api\src\processor.py", line 45, in _process_url
  |     asyncio.run(process_url(url))
  |     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  |   File "C:\<path>\Python313\Lib\asyncio\runners.py", line 194, in run
  |     return runner.run(main)
  |            ~~~~~~~~~~^^^^^^
  |   File "C:\<path>\Python313\Lib\asyncio\runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  |   File "C:\<path>\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
  |     return future.result()
  |            ~~~~~~~~~~~~~^^
  |   File "C:\<path>\crawler_api\src\lib.py", line 159, in process_url
  |     await crawler.build_graph(url)
  |   File "C:\<path>\crawler_api\src\lib.py", line 97, in build_graph
  |     async with asyncio.TaskGroup() as tg:
  |                ~~~~~~~~~~~~~~~~~^^
  |   File "C:\<path>\Python313\Lib\asyncio\taskgroups.py", line 154, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)       
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\<path>\crawler_api\src\lib.py", line 92, in crawl   
    |     await crawl(crawler, full_url, depth + 1)
    |   File "C:\<path>\crawler_api\src\lib.py", line 92, in crawl   
    |     await crawl(crawler, full_url, depth + 1)
    |   File "C:\<path>\crawler_api\src\lib.py", line 92, in crawl   
    |     await crawl(crawler, full_url, depth + 1)
    |   [Previous line repeated 7 more times]
    |   File "C:\<path>\crawler_api\src\lib.py", line 88, in crawl   
    |     full_url = urljoin(url, href.attrib["href"], allow_fragments=False)
    |   File "C:\<path>\Python313\Lib\urllib\parse.py", line 555, in urljoin
lib\parse.py", line 500, in urlsplit
    |     _check_bracketed_host(bracketed_host)
    |     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
    |   File "C:\<path>\Python313\Lib\urllib\parse.py", line 446, in _check_bracketed_host
    |     ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
    |   File "C:\<path>\Python313\Lib\ipaddress.py", line 54, in ip_address
    |     raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
    | ValueError: '.' does not appear to be an IPv4 or IPv6 address
    +------------------------------------
